name: Remove inactive users
on:
  push

jobs:
  remove_inactive_users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run script to remove inactive users
        run: |
          npm install -g github-user-activity
          github-user-activity remove --organization YOUR_ORGANIZATION_NAME --days 90
        env:
          TOKEN: ${{ secrets.TOKEN }}
